audio:
  sample_rate: 16000
  frame_length: 20
  frame_shift: 10
  n_mels: 80
  feature_extract_by: torchaudio

model:
  architecture: deepspeech2
  rnn_type: gru
  hidden_dim: 512
  num_layers: 5
  dropout: 0.1
